name: Frontend CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Debug repo structure
      - name: Show repo structure
        run: ls -R

      # Setup Node.js (Angular 20 requires Node.js 20+)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd product-catalog
          npm ci

      # Build Angular
      - name: Build Angular
        run: |
          cd Frontend/product-catalog
          npx ng build --configuration production

      # Deploy to Azure App Service
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "productangular" # 🔹 Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Frontend/product-catalog/dist/product-catalog # 🔹 Adjust if dist folder name differs
